services:
  akto-mongo:
    container_name: akto-mongo
    image: mongo:6.0.1
    restart: unless-stopped
    network:
      - akto-network
    volumes:
      - akto-mongodb:/data/db
    expose:
      - 27017

  akto-api-security-dashboard:
    image: aktosecurity/akto-api-security-dashboard:local
    container_name: akto
    restart: unless-stopped
    network:
      - akto-network
      - proxy
    env_file: ./docker.env
    expose: 
      - 8080
    depends_on:
      - akto-mongo
    
  akto-api-security-testing:
    image: aktosecurity/akto-api-testing:local
    container_name: akto-test
    restart: unless-stopped
    network:
      - akto-network
    env_file: ./docker.env
    depends_on:
      - akto-mongo    
  akto-puppeteer-replay:
    image: aktosecurity/akto-puppeteer-replay:latest
    container_name: akto-replay
    restart: unless-stopped
    network:
      - akto-network
    expose:
      - 3000
volumes:
  akto-mongodb:
networks:
  proxy:
    external: true
